version: "3.9"

services:
  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    # volumes:
    #  - .:/code
    ports:
      - 3888:8000
    depends_on:
      - db
    networks:
      - customnetwork
  db:
    image: postgres:13
    # restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5455:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      customnetwork:
        ipv4_address: 172.27.0.2
      
volumes:
  postgres_data:

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.27.0.0/16